### position.py
PAWN = 0
KNIGHT = 1
BISHOP = 2
ROOK = 3
KING = 4
QUEEN = 5

WHITE = 0
BLACK = 6
BOTH = 12
EMPTY = 13

### Move.py
QUIET = 0
CAPTURE = 1
DOUBLE_PAWN_PUSH = 2
KING_CASTLE = 3
QUEEN_CASTLE = 4
EN_PASSANT = 5
PROMOTION = 6
PROMOTION_CAPTURE = 7

## Zobrist.py
SEED = 120094

## transposition.py
EXACT = 0
LOWER_BOUND = 1
UPPER_BOUND = 2
NO_MATCH = -1
NOT_DEEP_ENOUGH = -2
NOT_USABLE = 0
USABLE = 1

## evaluate.py
PIECE_VALUES = {PAWN: 100, KNIGHT: 320, BISHOP: 330, ROOK: 500, QUEEN: 900, KING: 0}
PHASE_WEIGHTS = {PAWN: 0, KNIGHT: 1, BISHOP: 1, ROOK: 2, QUEEN: 4, KING: 0}
TOTAL_PHASE = 4*PHASE_WEIGHTS[KNIGHT] + 4*PHASE_WEIGHTS[BISHOP] + 4*PHASE_WEIGHTS[ROOK]  + 2*PHASE_WEIGHTS[QUEEN]

## search.py
INFINITY = 10**9
MATE_SCORE = 1000000
